//tealium universal tag - utag.51 ut4.0.202504290050, Copyright 2025 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.clearEmptyKeys=function(object){var key,required_list=["orderId","customerId","customerEmail","category","quantity","subTotal","sku"];for(key in object){if((object[key]===""||object[key]===undefined)&&(required_list.indexOf(key)===-1)){delete object[key];}}
return object;};u.isPlainEmail=function(email){var emailRegex=/^([A-Za-z0-9_\-.+])+@([A-Za-z0-9_\-.])+\.([A-Za-z]{2,})$/;return emailRegex.test(email);}
u.createProductCollection=function(obj){var i,collection=[],data={};for(i=0;i<obj.product_sku.length;i++){data.subTotal=obj.product_subTotal[i]||"";data.sku=obj.product_sku[i]||"";data.category=obj.product_category[i]||"";data.quantity=obj.product_quantity[i]||"";data.name=obj.product_name[i];data.brand=obj.product_brand[i];data.subcategory=obj.product_subcategory[i];data.mpn=obj.product_mpn[i];data.deliveryType=obj.product_deliveryType[i];data.referenceId=obj.product_referenceId[i];data.promoCodeDesc=obj.product_promoCodeDesc[i];data.totalDiscount=obj.product_totalDiscount[i];data.totalRebate=obj.product_totalRebate[i];data.discount=obj.product_discount[i];collection.push(u.clearEmptyKeys(data));data={};}
return collection;};u.map={"campaign.sessionIrClickId":"clickId","impact.orderId":"orderId","impact.note":"note","impact.actionTrackerId":"actionTrackerId","velocityIDHashed":"customerId"};u.extend=[function(a,b){try{if(1){if(b["ev.aemAnalyticsAbort"]&&b["ev.aemAnalyticsAbort"]==="true"){return false;}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['dom.url'].toString().toLowerCase().indexOf('join.velocityfrequentflyer.com/welcome'.toLowerCase())>-1){try{b['impact.orderId']=Math.floor((Math.random()*1000000000000)+1);}catch(e){};b['impact.actionTrackerId']='33198'}}catch(e){utag.DB(e);}}];u.loader_cb=function(a,b,c){utag.DB("send:51:CALLBACK");u.initialized=true;var i,key,custom_key,options={},properties={},properties_exclusions_list=["base_url","acid","event","actionTrackerId","domReady","tag","custom"];if(a==="view"&&u.data.event.indexOf("identify")===-1){u.data.event.unshift("identify");}
if(u.data.orderId&&u.data.event.indexOf("trackConversion")===-1){u.data.event.push("trackConversion");}
if(u.data.domReady){options.domReady=u.data.domReady;}
if(u.data.tag){options.tag=u.data.tag;}
if(u.isPlainEmail(u.data.customerId)){u.data.customerId="";utag.DB(u.id+": A plain email address was detected for customerId. Removing from Impact tracking call.");}
if(u.isPlainEmail(u.data.customerEmail)){u.data.customerEmail="";utag.DB(u.id+": A plain email address was detected for customerEmail. Removing from Impact tracking call.");}
for(i=0;i<u.data.event.length;i++){if(u.data.event[i]==="identify"){ire(u.data.event[i],{customerId:u.data.customerId,customerEmail:u.data.customerEmail});}else{if(u.data.event[i]==="trackConversion"){options.verifySiteDefinitionMatch=true;}
for(key in u.data){if(u.data.hasOwnProperty(key)&&key.indexOf("product_")===-1&&properties_exclusions_list.indexOf(key)===-1){properties[key]=u.data[key];}}
for(custom_key in u.data.custom){if(u.data.custom.hasOwnProperty(custom_key)){properties[custom_key]=u.data.custom[custom_key];}}
properties=u.clearEmptyKeys(properties);properties.items=u.createProductCollection(u.data);if(!u.data.actionTrackerId){utag.DB(u.id+": Required attribute actionTrackerId not populated.");}
ire(u.data.event[i],u.data.actionTrackerId,properties,options);}}
utag.DB("send:51:CALLBACK:COMPLETE");};u.callBack=function(){var data={};while(data=u.queue.shift()){u.data=data.data;u.loader_cb(data.a,data.b,data.c);}};u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:51");utag.DB(b);var c,d,e,f,h;u.data={"acid":"A3014068-9236-4349-8fa2-07649c1a0ab61","base_url":"//d.impactradius-event.com/","actionTrackerId":"","orderId":"","orderPromoCode":"","orderPromoCodeDesc":"","orderDiscount":"","orderRebate":"","orderSubTotalPreDiscount":"","orderSubTotalPostDiscount":"","orderShipping":"","orderTax":"","paymentType":"","locationName":"","locationType":"","locationId":"","giftPurchase":"","currencyCode":"","customerId":"","customerEmail":"","customerCity":"","customerRegion":"","customerPostCode":"","customerCountry":"","customerStatus":"","money1":"","money2":"","money3":"","date1":"","date2":"","date3":"","numeric1":"","numeric2":"","numeric3":"","text1":"","text2":"","text3":"","siteCategory":"","siteVersion":"","hearAboutUs":"","note":"","dispositionCode":"","phoneNumber":"","callerId":"","clickId":"","referenceId":"","test":"","product_name":[],"product_sku":[],"product_brand":[],"product_category":[],"product_subcategory":[],"product_quantity":[],"product_mpn":[],"product_deliveryType":[],"product_referenceId":[],"product_subTotal":[],"product_promoCode":[],"product_promoCodeDesc":[],"product_totalDiscount":[],"product_totalRebate":[],"product_discount":[],"domReady":"","tag":"","event":[],"custom":{}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:51:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(u.data.hasOwnProperty(e[f])){u.data[e[f]]=b[d];}else{u.data.custom[e[f]]=b[d];}}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){if(u.map[d]){u.data.event=u.data.event.concat(u.map[d].split(","));}}}}
utag.DB("send:51:MAPPINGS");utag.DB(u.data);u.data.orderId=u.data.orderId||b._corder||"";u.data.orderSubTotalPreDiscount=u.data.orderSubTotalPreDiscount||b._csubtotal||"";u.data.orderShipping=u.data.orderShipping||b._cship||"";u.data.orderTax=u.data.orderTax||b._ctax||"";u.data.currencyCode=u.data.currencyCode||b._ccurrency||"";u.data.orderPromoCode=u.data.orderPromoCode||b._cpromo||"";u.data.customerId=u.data.customerId||b._ccustid||"";u.data.customerCity=u.data.customerCity||b._ccity||"";u.data.customerRegion=u.data.customerRegion||b._cstate||"";u.data.customerPostCode=u.data.customerPostCode||b._czip||"";u.data.customerCountry=u.data.customerCountry||b._ccountry||"";if(u.data.product_name.length===0&&b._cprodname!==undefined){u.data.product_name=b._cprodname.slice(0);}
if(u.data.product_sku.length===0&&b._csku!==undefined){u.data.product_sku=b._csku.slice(0);}
if(u.data.product_brand.length===0&&b._cbrand!==undefined){u.data.product_brand=b._cbrand.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.data.product_subcategory.length===0&&b._ccat2!==undefined){u.data.product_subcategory=b._ccat2.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_subTotal.length===0&&b._cprice!==undefined){u.data.product_subTotal=b._cprice.slice(0);}
if(!u.data.acid){utag.DB(u.id+": Tag not fired: Required attribute acid not populated");return;}
u.data.base_url+=u.data.acid;if(!/\.js$/.test(u.data.base_url)){u.data.base_url+=".js";}
if(u.initialized){u.loader_cb(a,b,c);}else{u.queue.push({"data":u.data,"a":a,"b":b,"c":c});if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":"utag_51","attrs":{}});}}
utag.DB("send:51:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("51","virgin.velocity"));}catch(error){utag.DB(error);}
